### ISSUE TITLE
联系方式请求

### ISSUE THREAD

**Issue by AgainstWar** [Alaye-Dong/ElectroSmartCar_quad#1]
你好，请问能否提供下联系方式，有一些智能车相关事项想要交流。
> 可以通过AgainstWar@outlook.com联系到我

**Comment by Alaye-Dong** [comment]
已通过一谷歌邮箱发出回复

**Comment by Alaye-Dong** [comment]
> 你好，请问能否提供下联系方式，有一些智能车相关事项想要交流。
> 
> > 可以通过[AgainstWar@outlook.com](mailto:AgainstWar@outlook.com)联系到我

使用邮箱可能不方便，我们也可以直接在这个issue暂时交流
